#!/bin/bash
# DailyShowDownloader
# Usage: ddd <url of page>
# Downloads daily show episodes, transcoded into a nicer format
#
# This script depends on curl, rtmpdump and avidemux.
# For playback I recommend mplayer.
# Sometimes the sound is not in sync : /
# Suggestions welcome.
#

RTMPDUMP="rtmpdump" # the name of the binary

set -eu

if [ $# = 1 ] && [ ${#1} = 6 ] ; then
	ID="$1"
elif [ $# = 1 ] && echo "$1" | grep -E -q "http://media.mtvnservices.com/mgid:cms:[^:]+:comedycentral.com:[0-9]+" ; then
	ID=`echo "$1" | cut -d : -f 6`
elif [ $# = 1 ] && echo "$1" | grep -E -q "http://.+" ; then
	if ! ID=`curl -s "$1" | grep -E -m 1 -o "http://media.mtvnservices.com/mgid:cms:[^:]+:comedycentral.com:[0-9]+" | cut -d : -f 6` ; then
		echo "error: could not extract video id"
		exit 1
	fi
else
	echo "usage:"
	echo "	$0 \${ID}"
	echo "	$0 http://www.thedailyshow.com/full-episodes/\${ID}/title-of-the-episode"
	echo "	$0 http://www.thedailyshow.com/watch/some-kind-of-date/title-of-video"
	echo "	$0 http://www.comedycentral.com/colbertreport/full-episodes/index.jhtml?episodeId=\${ID}"
	echo "	$0 http://media.mtvnservices.com/mgid:cms:item:comedycentral.com:\${ID}"
	echo "	$0 http://media.mtvnservices.com/mgid:cms:video:comedycentral.com:\${ID}"
	echo "	$0 http://media.mtvnservices.com/mgid:cms:fullepisode:comedycentral.com:\${ID}"
	exit 1
fi

RTMPDUMP_OPTS="--swfsize 563963 --swfUrl http://media.mtvnservices.com/player/release/?v=3.14.0"
RTMPDUMP_OPTS="$RTMPDUMP_OPTS --swfhash 1155163cece179766c97fedce8933ccfccb9a553e47c1fabbb5faeacc4e8ad70"

GEN_URL="http://media.mtvnservices.com/player/config.jhtml?uri=mgid:cms:item:comedycentral.com:${ID}&group=entertainment&type=error"
PARTS=`curl -s "$GEN_URL" | grep media:content | grep -v bumper | cut -d \" -f 2`

AVIDEMUX_ARGS="--audio-codec copy --video-codec copy"
TMP="--load"

# download parts in parallel
for X in $PARTS ; do
	VIDEO_URL=`curl -s "$X" | grep edgefcs.net | tail -n 1 | cut -d '>' -f 2 | cut -d '<' -f 1`
	FILENAME=`basename "$VIDEO_URL"`
	echo "Downloading $VIDEO_URL -> $FILENAME"
	$RTMPDUMP $RTMPDUMP_OPTS -r "$VIDEO_URL" -o "$FILENAME" &
	AVIDEMUX_ARGS="$AVIDEMUX_ARGS $TMP $FILENAME"
	TMP="--append"
done
wait
