#!/bin/bash
# Usage: devtool [prefix] [optional test scripts]
# Wrapper for Node Devtool + (Mocha \ Gulp)

case "$1" in
	'gulp')
		echo "Using gulp devtool profile"
		shift
		/usr/bin/devtool ./node_modules/gulp/bin/gulp "$@"
		;;
	'mocha')
		echo "Using Mocha devtool profile"
		shift
		/usr/bin/devtool ./node_modules/mocha/bin/_mocha "$@"
		;;
	*)
		echo "Unknown devtool profile. Assuming literal path"
		/usr/bin/devtool "$@"
esac
