#!/bin/bash
# Use 'fd' + 'fzf' to pick a file to edit in VIM
#
# Usage: fdv [pattern]

# Use fd to find files matching the pattern and pipe to fzf
# Allow multiple selections with tab/shift+tab
FDV_SELECTED=$(\
		fd -- "${1:-.}" \
		| fzf \
			--multi \
			--preview 'bat --color=always --style=numbers --line-range=:500 {}' \
			--height 80% \
			--border
	)

# Check if any files were selected
if [ -n "$FDV_SELECTED" ]; then
	# Open each selected file with vi
	vi $FDV_SELECTED
else
	echo "No files selected"
fi
