#!/bin/bash
if [ "$#" -eq 0 ]; then
	echo "Usage: $0 [-1] <dictionary> [dictionary...]"
	echo "Returns a fortune file without the need to first compile a .dat file via strtofile"
	echo "Author: Matt Carter <m@ttcarter.com>"
	echo ""
	echo "-1	Assumes that there is one entry per line and that '%' should be automatically assumed every second line"
	exit 1
fi

if [ "$1" == '-1' ]; then
	PERLINE=1
	shift
else
	PERLINE=0
fi

# Compile .dat files
FORTUNES=
for FILE in "$@"; do
	if [ "$PERLINE" -eq 1 ]; then
		OUTFILE=`mktemp -t 'fortune-compile.XXXXXXXX'`
		while read LINE; do
			echo "$LINE" >>"$OUTFILE"
			echo "%" >>"$OUTFILE"
		done <"$FILE"
		strfile -s "$OUTFILE"
		FORTUNES="$FORTUNES $OUTFILE"
	else
		strfile -s "$FILE"
		FORTUNES="$FORTUNES $FILE"
	fi
done

fortune $FORTUNES

# Clean up
for FILE in "$FORTUNES"; do
	rm -f $FILE.dat
	if [ "$PERLINE" -eq 1 ]; then
		rm -f $FILE
	fi
done
