#!/bin/bash
# Undelete Git controlled files
# Usage: git undelete <files...>

for FILE in "$@"; do
	echo "Restore $FILE..."
	COMMIT=`git rev-list -n 1 HEAD -- "$FILE"`
	if [ -z "$COMMIT" ]; then
		echo "No commit found for $file"
	else
		echo " * Restoring from commit $COMMIT"
		git checkout $COMMIT^ -- "$FILE"
	fi
done
