#!/usr/bin/php -qC
<?
$usage = <<<END
Usage: htpasswd [password]
Create .htpasswd format password lists using the incomming password string
If no password is specified one will be randomly created.

Passwords should be entered into a .htpasswd file with the following format per line:
user:passhash
END;

if (count($_SERVER['argv']) == 1) { // Create password?
	$_SERVER['argv'][1] = '';
	$choices = '01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
	foreach (range(1, 8) as $bit)
		$_SERVER['argv'][1] .= substr($choices, rand(0, strlen($choices)), 1);
	echo "Using random password: {$_SERVER['argv'][1]}\n";
		
}

if ( (count($_SERVER['argv']) > 1) && (in_array($_SERVER['argv'][1], array('-h', '--help', '-?'))) )
	die("$usage\n");

foreach (array_slice($_SERVER['argv'], 1) as $pass)
	echo crypt($pass, rand(1,9999999)) . "\n";
?>
