#!/bin/bash
HELP="
Utility command functions for iDrive360

Usage: idrive <command>

Commands:

idrive help              This help screen

idrive start             Start the iDrive Cron + system task

idrive stop              Try to (politely) shut down the iDrive process

idrive kill              Try to agressively shut down any remaining iDrive processess
"

CMD="$1"
case "$CMD" in
	"help")
		echo "$HELP"
		exit
		;;

	"query")
		if [ "$(pgrep -cif idrive)" == 0 ]; then
			echo "iDrive is not running"
		else
			echo "iDrive is running"
		fi
		exit 0
		;;


	"start")
		if [ "$(pgrep -cif idrive)" == 0 ]; then
			echo "iDrive already running"
			exit 0
		fi

		echo "Starting main iDrive process"
		/opt/idrive360/Idrivelib/dependencies/python/idrive360 start

		echo "Installing Cron system unit"
		/opt/idrive360/Idrivelib/dependencies/python/idrive360 6

		echo "Starting Cron unit"
		sudo systemctl start idrive360cron

		exit 0
		;;

	"stop")
		if [ "$(pgrep -cif idrive)" == 0 ]; then
			echo "iDrive not running"
			exit 0
		fi

		echo "Stopping iDrive process"
		/opt/idrive360/Idrivelib/dependencies/python/idrive360 stop

		echo "Stop iDrive cron system unit"
		sudo systemctl stop idrive360cron

		exit 0
		;;

	"kill")
		if [ "$(pgrep -cif idrive)" == 0 ]; then
			echo "iDrive not running"
		else
			echo "Politely killing iDrive processes"
			pgrep -if idrive | grep -v $$ | sudo xargs kill

			if [ "$(pgrep -cif idrive)" -ge 1 ]; then
				echo "iDrive still running - waiting 10s + agressive kill"
				sleep 10

				if [ "$(pgrep -cif idrive)" -ge 1 ]; then
					echo "Agressively killing iDrive processes"
					pgrep -if idrive | grep -v $$ | sudo xargs kill -9
				fi
			fi
		fi

		exit 0
		;;

	*)
		echo "Unknown iDrive comamnd"
		exit 1
esac
