#!/bin/bash
# Lock the screen via the standard XFCE4 locking system
# Usage: lock-screen

# Kill cursr on non-Slab machines so it doesn't bugger up Slabs unlock
if [ `hostname` != 'Slab' ]; then
	echo "Killing session sharing daemons"
	pkill cursr
fi

echo "Locking screen"
xflock4 &
