#!/bin/bash
# Usage: loqsay -v [text...]
# Use the Loquendo service to translate text-to-speach
# Can be:
#	En-Simon,Kate,Elizabeth
#	USA-Dave,Susan,Kenneth

VOICE=Simon
BASEPATH="/inc/scripts/loqsaid"

TEXT=$@
echo $TEXT
TEXT=`echo $TEXT | tr -s '[:space:]' '+'`
TEXT=${TEXT%+}
mkdir -p "$BASEPATH/$VOICE"
SAIDPATH="$BASEPATH/$VOICE/$TEXT"
if [ ! -s "$SAIDPATH" ]; then
	curl -s -d "testo=$TEXT" -d "voce=$VOICE" -d "tipo=40" -d "play=Play" -e "http://actor.loquendo.com/actordemo/default.asp?voice=$VOICE" http://actor.loquendo.com/actordemo/waveform.asp -c loqsaid/cookiejar -L -H "HTTP_USER_AGENT:Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.12) Gecko/20050922 Fedora/1.0.7-1.1.fc3 Firefox/1.0.7" -H "HTTP_ACCEPT_LANGUAGE:en-us,en;q=0.5" -o "$SAIDPATH"
fi

plaympeg "$SAIDPATH" >/dev/null
