#!/bin/bash
# Run a command on all suitable files within a directory excluding certain ones
# Usage: nargs [xarg flags] <command>
#
# Excluded files include:
#     - bower_components/
#     - node_modules/
#     - sparks/
#     - vendor/
#     - .git directories
#     - All non-files
#
# All files are null-escaped and passed to xargs.
# Other xargs flags will also work if they preceed the command e.g. `-n1 echo`
#
# @author Matt Carter <m@ttcarter.com>
# @date 2015-06-04

find \
-not -path '*/node_modules/*' \
-not -path '*/bower_components/*' \
-not -path '*/vendor/*' \
-not -path '*/sparks/*' \
-not -path '*/.git/*' \
-not -name '.git' \
-type f \
-print0 \
| xargs -0 "$@"
