#!/bin/bash
# Usage: nogrep <expression> [additional paths]
# Variant of Grep that only searches JS files in NodeJS like projects (e.g. Ignoring module directories)
#
# Features:
#           * Case insensitive search assumed
#           * .git, node_modules, bower_components, build automatically ignored
#           * All RegExps are Perl standard rather

EXP="$1"
shift

if [ -d "node_modules" ]; then
	# Operating at root of Node project
	grep "$EXP" \
		-riP \
		--color=auto \
		--exclude-dir=bower_components \
		--exclude-dir=build \
		--exclude-dir=data \
		--exclude-dir=docs \
		--exclude-dir=dist \
		--exclude-dir=.git \
		--exclude-dir=node_modules \
		--exclude=package-lock.json \
		. \
		"$@"

else
	# Fallback to normal grep syntax
	if [ -z "$@" ]; then
		# No specific file names specified - use all
		grep "$EXP" --color=auto -P -r .
	else
		grep "$EXP" --color=auto -P -r "$@"
	fi
fi
