#!/bin/bash
# Usage: pdfcat <output.pdf> [files...]
#
# Helper application to concatinate and convert mutliple images or PDFs into one single PDF
#
# @author Matt Carter <M@ttCarter.com>

# Where to stick the converted files
TMPDIR=/tmp/pdfcat

OUTFILE="$1"
shift

if [ ${OUTFILE#*.} != 'pdf' ]; then
	echo "First parameter to pdfcat must be the output PDF file"
	exit 1
fi

mkdir $TMPDIR 2>/dev/null

for FILE in "$@"; do 
	BASE=${FILE%.*}
	EXT=${FILE#*.}

	if [ "$EXT" != "pdf" ]; then
		echo "Converting $FILE -> $BASE.pdf..."
		convert $FILE "$TMPDIR/$BASE.pdf"
	else
		echo "$FILE is already a PDF - skipping conversion"
		cp "$FILE" "$TMPDIR/$BASE"
	fi
done

echo "Concatinating all files into $OUTFILE..."
pdftk $TMPDIR/*.pdf cat output "$OUTFILE"
rm -rf "$TMPDIR"
