#!/usr/bin/php -qC
<?
$help = <<<END
Usage: PHPFilter <function> [strings...]
Feed incomming text though a PHP filter
Text can either be specified on the command line or fed one line at a time via STDIN
END;
$aliases = array( // Quick aliases
	'base64' => 'base64_encode'
);

$argv = array_slice($_SERVER['argv'], 1);
if ( !$argv || in_array($argv[0], array('-h', '--help')) )
	die("$help\n");

$filter = strtolower(array_shift($argv));
if (isset($aliases[$filter]))
	$filter = $aliases[$filter];

foreach ($argv as $blob)
	echo $filter($blob) . ' ';

if (!$argv) {
	$stdin = fopen('php://STDIN', 'r');
	while ($blob = fgets($stdin, 1024)) {
		$blob = rtrim($blob);
		echo $filter($blob) . "\n";
	}
	fclose($stdin);
}
?>
