#!/bin/bash
# Output PM2 logs with an optional RipGrep expression
# This function splices together dates and merges STDOUT / STDERR log files
# Usage: pm2-logs <match> [rip-grep-args]

LOGPATH="$HOME/.pm2/logs"

# Shift first param as grep expression, fixing it to a 'match all' if none
GREPEXP="${1:-.}"
shift

cd "$LOGPATH"

rg "$GREPEXP" "$@" *.log \
	| perl -pe 's/-(err|out)\.log:/:/g' \
	| sort --key=1 --field-separator=:
