#!/bin/bash
# Execute a program continuously until it returns exit 0
# Usage: retry <command>
#
# @author Matt Carter <m@ttcarter.com
# @date 2015-03-07

PREFIX_COLOR='\033[0;30m\033[47m'
PREFIX_RESET='\033[0m'
PREFIX="\e[1m\e[34m[RETRY]\e[0m "
RETRYCOUNT=0
SLEEP=2

echo -e "${PREFIX}Run $@"
while true; do
	"$@"
	EXIT="$?"
	if [ "$EXIT" != 0 ]; then
		RETRYCOUNT=$(( RETRYCOUNT +1 ))
		echo -e "${PREFIX_COLOR} RETRY #${RETRYCOUNT} ${PREFIX_RESET} Exit code '$EXIT' recieved, retrying..."
		sleep "$SLEEP"
	else
		echo -e "${PREFIX_COLOR} RETRY #${RETRYCOUNT} ${PREFIX_RESET} Program exited correctly, stopping"
		break
	fi
done
