#!/bin/bash
# Usage: scan [device]
#
# Simple Wifi ESSID scanner
# This script ouputs all found ESSID's in a simple list

if [ -n "$1" ]; then
	DEV="$1"
elif [ `hostname` == 'Dex' ]; then
	DEV=wlp2s0
else
	DEV=wlp3s0
fi

# Page the lister until we get some output
while [ -z "$OUTPUT" ]; do
	OUTPUT=`sudo iwlist "$DEV" scan 2>&1 | grep ESSID | sed -r 's/\s+ESSID:"(.*)"/\1/g' | sort | uniq`
	echo -n "."
	sleep 0.25
done

echo
echo "$OUTPUT"
