#!/usr/bin/perl
# Usage: cat file | shuffle
# Return a shuffled version of the input stream
# Author: Matt Carter <m@ttcarter.com>

sub fisher_yates_shuffle {
	my $array = shift;
	my $i;
	for ($i = @$array; --$i; ) {
		my $j = int rand ($i+1);
		next if $i == $j;
		@$array[$i,$j] = @$array[$j,$i];
	}
}

while(<>) {
	chomp;
	push @input, $_;
}

&fisher_yates_shuffle(\@input);
print join("\n",@input);
