#!/bin/bash
# Start a Tmux session with a split of `glances` on top + `pm2 logs` on bottom
# Usage: sup [cmd1] [cmd2]
# cmd1   (default `glances`) specify an alternative command to run at the top of the window

CMD1=$1
CMD2=$2

if [ -z "$CMD1" ]; then
	if [ `which btm >/dev/null; echo "$?"` == 0 ]; then
		CMD1=btm
	elif [ `which ytop >/dev/null; echo "$?"` == 0 ]; then
		CMD1=ytop
	elif [ `which glances >/dev/null; echo "$?"` == 0 ]; then
		CMD1=glances
	elif [ `which htop >/dev/null; echo "$?"` == 0 ]; then
		CMD1=htop
	else
		CMD1=top
	fi
fi

if [ -z "$CMD2" ]; then
	CMD2="pm2 logs"
fi

if [ `tmux has-session; echo $?` == 0 ]; then
	tmux attach-session -t sup
else
	tmux new-session -d -s sup $CMD1
	tmux split-window -t sup $CMD2
	tmux attach-session -t sup
fi
