#!/bin/bash
# Start a Tmux session with a split of `glances` on top + `pm2 logs` on bottom
# Usage: sup [cmd1] [cmd2]
# cmd1   (default `glances`) specify an alternative command to run at the top of the window

CMD1=$1
CMD2=$2

if [ -z "$CMD1" ]; then
	CMD1="glances"
fi

if [ -z "$CMD2" ]; then
	CMD2="pm2 logs"
fi

tmux new-session -d -s sup $CMD1
tmux split-window -t sup $CMD2
tmux attach-session -t sup
