#!/bin/bash
# Switch the MAC address on an adapter
# Requires: macchanger

DEV=wlp3s0

sudo nmcli device disconnect wlp3s0
sudo ifconfig $DEV down
sudo macchanger -a $DEV
sudo ifconfig $DEV up
sudo nmcli device connect wlp3s0

google-chrome --incognito 'http://news.bbc.co.uk'
