#!/bin/bash
# Wait for a PID to finish, paging it every second
# Usage: waitpid <PID> && cmd

PID="$1"
echo "Waiting for PID '$PID' to exit..."

while true; do
	ps -p "$PID" >/dev/null 2>&1
	if [ "$?" != 0 ]; then
		echo "Process finished. Exiting."
		exit 0
	fi
	sleep 1
done
