#!/bin/bash
# Script to watch what files Dropbox is currently accessing
#
# Usage: watch-dropbox
#

# Prefix of DB filesystem
PREFIX="$HOME/Dropbox"

DBPID=`ps -C 'dropbox' -o '%p' | tr -d ' \nPID'` 
if [ -z "$DBPID" ]; then
	echo "No dropbox PID can be found"
	exit 1
fi

echo "Watching Dropbox (PID=$DBPID)..."

sudo strace -p "$DBPID" -f --decode-fds=path -e trace=open,openat 2>&1 | grep "$PREFIX" | perl -pe 's/^.*= \d+<(.+?)>$/$1/gm'
