#!/bin/bash
# Cleans a given input XML file, overwriting the original
# Usage: xmlclean <path>

if [ -z "$1" ]; then
	echo "Usage: $0 <file>"
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "Error: File '$1' not found"
	exit 1
fi

temp=$(mktemp)
xmllint --format "$1" --output "$temp" && mv "$temp" "$1" || rm -f "$temp"
